server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /api
logging:
  config: classpath:logback/logback-spring-${spring.profiles.active}.xml
spring:
  application:
    name: yys-paas-server-template
  mvc.throw-exception-if-no-handler-found: true
  resources.add-mappings: false
  datasource:
    url: jdbc:mysql://172.31.186.43:4001/kb-spark?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: Fpva_123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  #redis 配置
  #  redis:
  #    host: 172.31.242.161
  #    port: 6370
  #    password: G_8NxEfcuyOmqMg
  #    timeout: 10000
  #    database: 1
  #    lettuce:
  #      pool:
  #        max-active: 8
  #        max-idle: 8
  #        max-wait: 10000
  #        min-idle: 0
  messages:
    encoding: UTF-8
    basename: classpath:i18n/messages
    cache-second: 3600

# mybatis配置
mybatis-plus:
  global-config:
    db-config:
      id-type: uuid
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.iflytek.yys.business.model.entity
  mapper-locations: classpath*:mapper/*.xml